apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: redis-tag
  name: towfeeq
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis-tag
  template:
    metadata:
      labels:
        run: redis-tag
    spec:
      containers:
      - name: redis-container
        image: 11101998/redpy:v4
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: towfeeq
spec:
  selector:
    run: redis-tag
  ports:
    - name: redis-port
      port: 5050
      targetPort: 6379

